# -*- mode: python ; coding: utf-8 -*-

import os
import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['backend.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        # Django
        'django',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.auth.hashers',
        'django.contrib.auth.password_validation',
        'django.contrib.auth.tokens',
        'django.contrib.auth.management',
        'django.contrib.auth.migrations',
        'django.contrib.contenttypes.management',
        'django.contrib.sessions.management',
        'django.contrib.messages.management',
        'django.contrib.staticfiles.management',
        'django.contrib.admin.migrations',
        'django.contrib.auth.migrations',
        'django.contrib.contenttypes.migrations',
        'django.contrib.sessions.migrations',
        'django.contrib.messages.migrations',
        'django.contrib.staticfiles.migrations',
        'django.utils',
        'django.template',
        'django.templatetags',
        'django.conf',
        'django.core',
        'django.db',
        'django.forms',
        'django.http',
        'django.shortcuts',
        'django.urls',
        'django.views',
        'django.middleware',
        # DRF
        'rest_framework',
        'rest_framework_simplejwt',
        'rest_framework.authtoken',
        'rest_framework.authtoken.admin',
        'rest_framework.authtoken.migrations',
        'rest_framework.authtoken.models',
        'rest_framework.authtoken.serializers',
        'rest_framework.authtoken.views',
        # Third party
        'corsheaders',
        'django_filters',
        'drf_spectacular',
        'drf_spectacular.contrib',
        'crum',
        'reportlab',
        'reportlab.graphics',
        'reportlab.lib',
        'reportlab.platypus',
        'reportlab.pdfbase',
        'reportlab.pdfgen',
        'PIL',
        'PIL._imaging',
        'firebase_admin',
        'firebase_admin._snowflake',
        'waitress',
        # Project apps
        'core',
        'my_auth',
        'users',
        'products',
        'sales',
        'tasa',
        'system',
        # Migrations
        'core.migrations',
        'my_auth.migrations',
        'users.migrations',
        'products.migrations',
        'sales.migrations',
        'system.migrations',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'cairo',
        'PyQt5',
        'PySide2',
        'PyQt6',
        'PySide6',
    ],
    runtime_hooks=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='venta-control-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
