# Generated by Django 6.0.1 on 2026-02-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_products',
            old_name='sale_id',
            new_name='sale',
        ),
        migrations.AddField(
            model_name='sale_products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale_products',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
