# Generated by Django 6.0.1 on 2026-02-03 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_rename_sale_id_sale_products_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_products',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
