# Generated by Django 6.0.1 on 2026-02-04 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_products',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='sales.sales'),
        ),
    ]
