# Generated by Django 5.2.12 on 2026-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_products_id_alter_sales_id_salestype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_products',
            name='bs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='bs_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
