# Generated by Django 6.0.1 on 2026-02-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='primer_apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primer_nombre',
            new_name='last_name',
        ),
    ]
