# Generated by Django 6.0.1 on 2026-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_primer_apellido_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
