# Generated by Django 6.0.1 on 2026-02-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_middle_name_user_second_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
