# Generated by Django 5.2.12 on 2026-04-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_middle_name_alter_user_second_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('dashboard', 'Acceder al dashboard')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
